// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeudDlOz1ZiYAYiQvT3GT4XgvbJOGCNpY',
    appId: '1:875418259968:web:28d5ee2f5e49f53f3abee5',
    messagingSenderId: '875418259968',
    projectId: 'mhealth-49991',
    authDomain: 'mhealth-49991.firebaseapp.com',
    storageBucket: 'mhealth-49991.appspot.com',
    measurementId: 'G-HBD6G22L7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0NP4tS2PrW01SQSbvGWtEHjN6HF3RYI',
    appId: '1:875418259968:android:6310f968a477745f3abee5',
    messagingSenderId: '875418259968',
    projectId: 'mhealth-49991',
    storageBucket: 'mhealth-49991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2RC6_QpfKUeyDZ24nM7D--xiFy_Q0bPE',
    appId: '1:875418259968:ios:6fcb2a5f4d1174323abee5',
    messagingSenderId: '875418259968',
    projectId: 'mhealth-49991',
    storageBucket: 'mhealth-49991.appspot.com',
    iosClientId: '875418259968-leje3ivlh1udnut9m73pl089gbvksiqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.baDepression',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2RC6_QpfKUeyDZ24nM7D--xiFy_Q0bPE',
    appId: '1:875418259968:ios:6fcb2a5f4d1174323abee5',
    messagingSenderId: '875418259968',
    projectId: 'mhealth-49991',
    storageBucket: 'mhealth-49991.appspot.com',
    iosClientId: '875418259968-leje3ivlh1udnut9m73pl089gbvksiqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.baDepression',
  );
}
